[package]
name = "eco-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
itertools = "0.11.0"
log = "0.4.20"
rand = "0.8.5"
rayon = "1.10.0"
